---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  namespace: cluster-observabilit-tenant
  name: cluster-observability-operator-1.0
spec:
  releasePlan: cluster-observability-operator-1-0-prod 
  snapshot: cluster-observability-operator-1-0-v9vgh
  data:
    releaseNotes:
      type: RHSA
      topic: "Cluster Observability Operator 1.0.0 release- prod."
      issues:
        fixed:
          - id: COO-32
            source: issues.redhat.com
          - id: COO-319
            source: issues.redhat.com
          - id: COO-584
            source: issues.redhat.com
          - id: COO-601
            source: issues.redhat.com
      cves:
        - key: CVE-2023-26159 
          component: coo-prometheus-container
        - key: CVE-2024-28849
          component: coo-prometheus-container
      references:
        - https://access.redhat.com/security/updates/classification
        - https://docs.openshift.com/container-platform/4.17/observability/cluster_observability_operator/cluster-observability-operator-release-notes.html
